import type { YieldStrategy } from "@yieldpilot/shared";
import type { VenueAdapter } from "./base-adapter";

export class MockKaminoAdapter implements VenueAdapter {
  venue = "kamino";

  async fetchStrategies(): Promise<YieldStrategy[]> {
    return [
      {
        id: "kamino-usdc-lending",
        venue: "kamino",
        vaultName: "Kamino USDC Lending",
        vaultAddress: "KmnUSDCv1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        tokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        tokenSymbol: "USDC",
        strategyType: "lending",
        apyPct: 5.8,
        netApyPct: 5.2,
        tvlUsd: 45_000_000,
        availableLiquidityUsd: 12_000_000,
        withdrawalLatency: "instant",
        riskTier: "low",
        riskTags: ["audited", "battle-tested"],
        minDeposit: 1,
        maxCapacity: 100_000_000,
        confidenceScore: 0.95,
        metadata: { audited: true, ageDays: 365, protocol: "Kamino Finance" },
        fetchedAt: new Date(),
      },
      {
        id: "kamino-usdt-lending",
        venue: "kamino",
        vaultName: "Kamino USDT Lending",
        vaultAddress: "KmnUSDTv1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        tokenMint: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
        tokenSymbol: "USDT",
        strategyType: "lending",
        apyPct: 4.9,
        netApyPct: 4.4,
        tvlUsd: 28_000_000,
        availableLiquidityUsd: 8_000_000,
        withdrawalLatency: "instant",
        riskTier: "low",
        riskTags: ["audited", "battle-tested"],
        minDeposit: 1,
        maxCapacity: 80_000_000,
        confidenceScore: 0.93,
        metadata: { audited: true, ageDays: 300, protocol: "Kamino Finance" },
        fetchedAt: new Date(),
      },
      {
        id: "kamino-usdc-usdt-lp",
        venue: "kamino",
        vaultName: "Kamino USDC-USDT LP",
        vaultAddress: "KmnLPv1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        tokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        tokenSymbol: "USDC",
        strategyType: "liquidity",
        apyPct: 8.2,
        netApyPct: 7.1,
        tvlUsd: 12_000_000,
        availableLiquidityUsd: 4_000_000,
        withdrawalLatency: "instant",
        riskTier: "medium",
        riskTags: ["audited", "impermanent-loss"],
        minDeposit: 100,
        maxCapacity: 50_000_000,
        confidenceScore: 0.85,
        metadata: { audited: true, ageDays: 180, impermanentLossRisk: true },
        fetchedAt: new Date(),
      },
      {
        id: "kamino-usdc-multiply",
        venue: "kamino",
        vaultName: "Kamino USDC Multiply",
        vaultAddress: "KmnMULv1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        tokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        tokenSymbol: "USDC",
        strategyType: "lending",
        apyPct: 12.5,
        netApyPct: 10.8,
        tvlUsd: 3_500_000,
        availableLiquidityUsd: 1_200_000,
        withdrawalLatency: "instant",
        riskTier: "high",
        riskTags: ["audited", "leveraged"],
        minDeposit: 500,
        maxCapacity: 20_000_000,
        confidenceScore: 0.75,
        metadata: { audited: true, ageDays: 90, leveraged: true },
        fetchedAt: new Date(),
      },
    ];
  }
}
